# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QInputDialog, QDialogButtonBox, QWidget, QButtonGroup, QVBoxLayout, QRadioButton, QDialog
from PyQt5.QtCore import Qt
from model.parts import DeckRadioButton
from .dialog import SelectionDialog


class UiMainWindow(object):
    def setup_ui(self, main_window, controller):
        self.controller = controller
        self.controller.on_startup()

        main_window.setObjectName("Learnables")
        main_window.resize(480, 640)

        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("central_widget")

        self.mainWidget = QtWidgets.QStackedWidget(self.centralwidget)  # Vertical Stacked Widget
        self.mainWidget.setGeometry(QtCore.QRect(10, 10, 451, 571))
        self.mainWidget.setObjectName("main_widget")

        # Start Page
        self.startPage = QtWidgets.QWidget()
        self.startPage.setObjectName("start_page")

        self.startVLayout = QtWidgets.QVBoxLayout(self.startPage)
        self.startVLayout.setSpacing(0)
        self.startVLayout.setObjectName("start_vlayout")
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.startVLayout.addItem(spacerItem)

        self.btn_cards = QtWidgets.QPushButton(self.startPage)
        self.btn_cards.clicked.connect(self.open_cards)
        self.btn_cards.setObjectName("button_cards")

        self.startVLayout.addWidget(self.btn_cards)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.startVLayout.addItem(spacerItem1)

        self.btn_decks = QtWidgets.QPushButton(self.startPage)
        self.btn_decks.clicked.connect(self.open_decks)
        self.btn_decks.setObjectName("button_decks")
        self.startVLayout.addWidget(self.btn_decks)

        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.startVLayout.addItem(spacerItem2)

        self.btn_learn = QtWidgets.QPushButton(self.startPage)
        self.btn_learn.clicked.connect(self.open_learn)
        self.btn_learn.setObjectName("button_learn")
        self.startVLayout.addWidget(self.btn_learn)

        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.startVLayout.addItem(spacerItem3)

        self.btn_start_settings = QtWidgets.QPushButton(self.startPage)
        self.btn_start_settings.setObjectName("btn_start_settings")
        self.startVLayout.addWidget(self.btn_start_settings)

        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.startVLayout.addItem(spacerItem4)

        self.mainWidget.addWidget(self.startPage)

        # Cards Page
        # TODO: wenn neue karten hinzugefügt werden, sind sie innerhalb von anderen karten
        self.cardsPage = QtWidgets.QWidget()

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardsPage.sizePolicy().hasHeightForWidth())
        self.cardsPage.setSizePolicy(sizePolicy)

        self.cardsPage.setObjectName("cards_page")
        self.cardsVLayout = QtWidgets.QWidget(self.cardsPage)
        self.cardsVLayout.setGeometry(QtCore.QRect(0, 0, 451, 571))
        self.cardsVLayout.setObjectName("cards_vlayout")

        self.cardsContentLayout = QtWidgets.QVBoxLayout(self.cardsVLayout)
        self.cardsContentLayout.setContentsMargins(0, 0, 0, 0)
        self.cardsContentLayout.setObjectName("cards_content_layout")

        self.cardsScrollArea = QtWidgets.QScrollArea(self.cardsVLayout)
        self.cardsScrollArea.setWidgetResizable(True)
        self.cardsScrollArea.setObjectName("cards_scroll_area")
        self.cardsContent = QtWidgets.QWidget()
        self.cardsContent.setGeometry(QtCore.QRect(0, 0, 447, 507))
        self.cardsContent.setObjectName("cards_content")
        self.cardsScrollArea.setWidget(self.cardsContent)
        self.cardsScrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.cardsScrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.cardsContentLayout.addWidget(self.cardsScrollArea)

        self.btn_add_card = QtWidgets.QPushButton(self.cardsVLayout)
        self.btn_add_card.clicked.connect(self.add_card)
        self.btn_add_card.setObjectName("btn_add_card")
        self.cardsContentLayout.addWidget(self.btn_add_card)

        self.cards_menu = QtWidgets.QHBoxLayout()
        self.cards_menu.setObjectName("cards_menu")
        self.btn_main_menu = QtWidgets.QPushButton(self.cardsVLayout)
        self.btn_main_menu.clicked.connect(lambda: self.mainWidget.setCurrentIndex(0))
        self.btn_main_menu.setObjectName("btn_main_menu")
        self.cards_menu.addWidget(self.btn_main_menu)

        self.btn_settings_cards = QtWidgets.QPushButton(self.cardsVLayout)
        self.btn_settings_cards.setObjectName("btn_settings_cards")
        self.btn_settings_cards.clicked.connect(self.open_settings)
        self.cards_menu.addWidget(self.btn_settings_cards)

        self.cardsContentLayout.addLayout(self.cards_menu)
        self.mainWidget.addWidget(self.cardsPage)

        # Decks Page
        self.decksPage = QtWidgets.QWidget()
        self.decksPage.setObjectName("decks_page")
        self.decksVLayout = QtWidgets.QWidget(self.decksPage)

        self.decksVLayout.setGeometry(QtCore.QRect(0, 0, 451, 571))
        self.decksVLayout.setObjectName("decks_vlayout")

        self.decksContentLayout = QtWidgets.QVBoxLayout(self.decksVLayout)
        self.decksContentLayout.setContentsMargins(0, 0, 0, 0)
        self.decksContentLayout.setObjectName("decks_content_layout")

        self.decksScrollArea = QtWidgets.QScrollArea(self.decksVLayout)
        self.decksScrollArea.setWidgetResizable(True)
        self.decksScrollArea.setObjectName("decks_scroll_area")
        self.decksContents = QtWidgets.QWidget()
        self.decksContents.setGeometry(QtCore.QRect(0, 0, 447, 507))
        self.decksContents.setObjectName("decks_contents")
        self.cardsScrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.cardsScrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.decksScrollArea.setWidget(self.decksContents)
        self.decksContentLayout.addWidget(self.decksScrollArea)

        self.btn_add_decks = QtWidgets.QPushButton(self.decksVLayout)
        self.btn_add_decks.setObjectName("btn_add_decks")
        self.btn_add_decks.clicked.connect(self.add_deck)
        self.decksContentLayout.addWidget(self.btn_add_decks)

        self.decks_menu = QtWidgets.QHBoxLayout()
        self.decks_menu.setObjectName("decks_menu")

        self.btn_decks_main_menu = QtWidgets.QPushButton(self.decksVLayout)
        self.btn_decks_main_menu.clicked.connect(lambda: self.mainWidget.setCurrentIndex(0))
        self.btn_decks_main_menu.setObjectName("btn_decks_main_menu")
        self.decks_menu.addWidget(self.btn_decks_main_menu)

        self.btn_settings_decks = QtWidgets.QPushButton(self.decksVLayout)
        self.btn_settings_decks.setObjectName("btn_settings_decks")
        self.btn_settings_decks.clicked.connect(self.open_settings)
        self.decks_menu.addWidget(self.btn_settings_decks)

        self.decksContentLayout.addLayout(self.decks_menu)

        self.mainWidget.addWidget(self.decksPage)

        # Learn Page
        self.learnPage = QtWidgets.QWidget()
        self.learnPage.setObjectName("learn_page")
        self.contentVLayout = QtWidgets.QWidget(self.learnPage)

        self.contentVLayout.setGeometry(QtCore.QRect(0, 0, 451, 571))
        self.contentVLayout.setObjectName("content_layout")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.contentVLayout)

        self.verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")

        # TODO: dieses label muss mit den richtigen karten ausgetauscht werden!
        self.dummy_label = QtWidgets.QLabel(self.contentVLayout)
        self.dummy_label.setObjectName("dummy_label")
        self.verticalLayout_1.addWidget(self.dummy_label)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.learn_menu = QtWidgets.QHBoxLayout()
        self.learn_menu.setObjectName("learn_menu")

        self.btn_back = QtWidgets.QPushButton(self.contentVLayout)
        self.btn_back.setObjectName("btn_back")
        self.btn_back.clicked.connect(self.back)
        self.learn_menu.addWidget(self.btn_back)

        self.btn_check = QtWidgets.QPushButton(self.contentVLayout)
        self.btn_check.setObjectName("btn_back")
        self.btn_check.clicked.connect(self.checked)
        self.learn_menu.addWidget(self.btn_check)

        self.btn_failed = QtWidgets.QPushButton(self.contentVLayout)
        self.btn_failed.setObjectName("btn_failed")
        self.btn_failed.clicked.connect(self.failed)
        self.learn_menu.addWidget(self.btn_failed)

        self.btn_next = QtWidgets.QPushButton(self.contentVLayout)
        self.btn_next.setObjectName("btn_next")
        self.btn_next.clicked.connect(self.skip)
        self.learn_menu.addWidget(self.btn_next)

        self.verticalLayout_2.addLayout(self.learn_menu)

        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")

        self.btn_learn_main_menu = QtWidgets.QPushButton(self.contentVLayout)
        self.btn_learn_main_menu.clicked.connect(lambda: self.mainWidget.setCurrentIndex(0))
        self.btn_learn_main_menu.setObjectName("btn_learn_main_menu")
        self.horizontalLayout_1.addWidget(self.btn_learn_main_menu)

        self.btn_learn_settings = QtWidgets.QPushButton(self.contentVLayout)
        self.btn_learn_settings.setObjectName("btn_learn_settings")
        self.btn_learn_settings.clicked.connect(self.open_settings)
        self.horizontalLayout_1.addWidget(self.btn_learn_settings)

        self.verticalLayout_2.addLayout(self.horizontalLayout_1)
        self.verticalLayout_1.addLayout(self.verticalLayout_2)

        self.mainWidget.addWidget(self.learnPage)
        main_window.setCentralWidget(self.centralwidget)

        # Menu bar
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.re_translate_ui(main_window)
        self.mainWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def re_translate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_cards.setText(_translate("MainWindow", "Karten"))
        self.btn_decks.setText(_translate("MainWindow", "Decks"))
        self.btn_learn.setText(_translate("MainWindow", "Lernen"))
        self.btn_start_settings.setText(_translate("MainWindow", "Einstellungen"))
        self.btn_add_card.setText(_translate("MainWindow", "+"))
        self.btn_main_menu.setText(_translate("MainWindow", "Startseite"))
        self.btn_settings_cards.setText(_translate("MainWindow", "Einstellungen"))
        self.btn_add_decks.setText(_translate("MainWindow", "+"))
        self.btn_decks_main_menu.setText(_translate("MainWindow", "Startseite"))
        self.btn_settings_decks.setText(_translate("MainWindow", "Einstellungen"))
        self.dummy_label.setText(_translate("MainWindow", "TextLabel"))
        self.btn_back.setText(_translate("MainWindow", "←"))
        self.btn_check.setText(_translate("MainWindow", "✔"))
        self.btn_failed.setText(_translate("MainWindow", "✘"))
        self.btn_next.setText(_translate("MainWindow", "→"))
        self.btn_learn_main_menu.setText(_translate("MainWindow", "Startseite"))
        self.btn_learn_settings.setText(_translate("MainWindow", "Einstellungen"))

    def open_settings(self):
        pass

    def open_cards(self):
        self.mainWidget.setCurrentIndex(1)
        cards = self.controller.get_cards()
        vbox = QtWidgets.QVBoxLayout()

        for card in cards:
            vbox.addWidget(card)

        self.cardsContent.setLayout(vbox)

    def add_card(self):
        #print(f"{self.controller.get_cards()}\n")
        front, ok = QInputDialog.getText(self.mainWidget, "Neue Karte erstellen", "Vorderseite: ")
        #print(front)
        if ok:
            back, ok = QInputDialog.getText(self.mainWidget, "Neue Karte erstellen", "Rückseite: ")
            #print(back)
            if ok:
                new_card = self.controller.add_card(front, back)
                #print(f"front {front}, back {back}, card: {new_card}")
                self.cardsContent.layout().addWidget(new_card)
                self.cardsContent.update()

    def open_decks(self):
        self.mainWidget.setCurrentIndex(2)
        decks = self.controller.get_decks()
        vbox = QtWidgets.QVBoxLayout()

        for deck in decks:
            #print(deck)
            vbox.addWidget(deck)

        self.cardsContent.setLayout(vbox)

    def add_deck(self):
        pass

    def add_card_to_deck(self):
        pass

    def open_learn(self):
        SelectionDialog(self.controller.get_decks(), self.controller)
        self.dummy_label.setText(self.controller.selected_deck.cards[0])
        self.verticalLayout_1.update()
        self.mainWidget.setCurrentIndex(3)

    def back(self):
        pass

    def forward(self):
        pass

    def checked(self):
        pass

    def failed(self):
        pass

    def skip(self):
        pass
